name: Build solution

on:
  push:
    branches:
    - main
    - feature/*
  pull_request:
    branches:
    - main
    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      SOLUTION: 'TeamsMonitor.sln'
      PROJECT: 'src/TeamsMonitor.Tool/TeamsMonitor.csproj'

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: | 
          6.x
          7.x
          8.x

    - name: Restore dependencies
      run: |
        dotnet restore $PROJECT


    - name: Build
      run: dotnet build $PROJECT --configuration $BUILD_CONFIG --no-restore

  build-app:

    env:
      BUILD_CONFIG: 'Release'
      PROJECT: '.\src\TeamsMonitor.Tray\TeamsMonitor.Tray.csproj'

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-dotnet@v3
      with:
        dotnet-version: | 
          6.x
          7.x
          8.x

    - name: Restore dependencies
      run: |
        dotnet restore $PROJECT


    - name: Build
      run: dotnet build --configuration $BUILD_CONFIG --no-restore $PROJECT
